### ISSUE TITLE
Circle ci artefact urls

### ISSUE THREAD

**Issue by YOU54F** [YOU54F/cypress-slack-reporter#1088]
Pretty sure circleci have deprecated the old endpoint we used to use to construct the links to the test artefacts.

Will dig out the doc links and fill in with more detail later :)

**Comment by dthisner** [comment]
Yeah, looks like they changed the format
Old way: 
```
https://${CI_BUILD_NUM}-${CI_PROJECT_ID}-gh.circle-artifacts.com/0/cypress/reports/mochareports/report.html
```
New Way:
```
https://output.circle-artifacts.com/output/job/${JOB-ID}/artifacts/0/cypress/reports/mochareports/report.html
```

**Comment by YOU54F** [comment]
thanks @dthisner release going out now 👍🏾
