### ISSUE TITLE
CircleCI artifact link updated again

### ISSUE THREAD

**Issue by claudiamatosa** [YOU54F/cypress-slack-reporter#472]
Hi there,

I think CircleCI has updated their artifact links again, and am happy to submit a pull request to fix this, but wanted to check in with you first (in case I've got a setting wrong and this can be fixed in a different way).

I am on version 0.5.5.

I have `CIRCLE_PROJECT_ID` set.

The report link that is being posted into slack is something like this:

```
https://2334-92384-gh.circle-artifacts.com/0/cypress/reports/mocha-report/mochawesome-report/mochawesome.html
```

But the only way that I can access the report is via something like this:

```
https://2334-92384-gh.circle-artifacts.com/0/~/project/test/cypress/reports/mocha-report/mochawesome-report/mochawesome.html
```

So the generated link is missing this bit: `~/project/test/`

My package.json is at the same level as that `cypress` folder.

Would it make sense to add an extra environment variable (or setting) to allow specifying this prefix?

**Comment by YOU54F** [comment]
Hey thanks for the report,

I may be because I used to get the current working directory and prefixed onto the reportDir path. 

https://github.com/YOU54F/cypress-slack-reporter/blob/7fa3c8f0ea9b53fe1e955b18efd995a7e84898e0/src/index.ts#L30

You can pass your full path with `-- report-dir` command line option.

Please feel free to submit a PR, I will test out the current state of circles api in the morning.

**Comment by claudiamatosa** [comment]
Unfortunately, the artifact link works with

```
https://2334-92384-gh.circle-artifacts.com/0/~/project/test/cypress/reports/mocha-report/mochawesome-report/mochawesome.html
```

But if we replace `~` with `/home/circleci` it doesn't reach the artifact, which means that `process.env.PWD` won't build the correct link.

In addition, if I pass `~/project/test/cypress/reports/mocha-report/mochawesome-report` as `reportDir` (with no quotes), the path ends up being resolved to the home dir, and I end up with a link that looks like `https://2334-92384-gh.circle-artifacts.com/0/home/circleci/project/test/cypress/reports/mocha-report/mochawesome-report/mochawesome.html`.

If I pass it with quotes, `cypress-slack-reporter` fails, saying that it was unable to resolve the path.

This is where I am no, but didn't have much time today, so will have a look later!

**Comment by rostradamus** [comment]
For those who are looking for the solution, there is a workaround by setting a destination option in store_artifacts job in config.yml (CircleCI).
``` 
- store_artifacts:
          path: ~/path/to/cypress/videos
          destination: cypress/videos
```
will allow you to access artifacts through 
https://${CI_BUILD_NUM}-${CI_PROJECT_ID}-gh.circle-artifacts.com/0/cypress/videos/some_test_result.mp4

This is what it says on CircleCI Documentation:
```
Currently, store_artifacts has two keys: path and destination.

path is a path to the file or directory to be uploaded as artifacts.
destination (Optional) is a prefix added to the artifact paths in the artifacts API. The directory of the file specified in path is used as the default.
```

**Comment by claudiamatosa** [comment]
Thank you very much @rostradamus, worked perfectly!

**Comment by YOU54F** [comment]
thanks @rostradamus 

Any of you kind chap and chapettes care to make a PR to update the readme? It would be very much apprieciated

**Comment by saikatharryc** [comment]
will it help setting custom URL? you can pass it from the CLI itself? 
cause this link seems like it is not static and consistent at all. and we already have custom option, not sure if that will help!

**Comment by YOU54F** [comment]
@claudiamatosa @rostradamus now added instructions to README, thank you very much all. hope this addresses this issue, and you are happy with it being closed. If not, give us a shout :)
