### ISSUE TITLE
Custom URI, for notifications link

### ISSUE THREAD

**Issue by kevindepoortere** [YOU54F/cypress-slack-reporter#497]
Hello,

First of all, many thanks for the good job, your plugin is really usefull.
I would like to know if you could offer an option for a custom base URI, which allow a user to pass a custom BASE_URI for the videos and screenshots links.

For example if you put 
`npx cypress-slack-reporter --ci-provider none --vcs-provider none`
Do you think it will be possible to offer a custom URI which allow to _artefactUrl
For the moment, I replace 'default' value in getArtefactUrl() but it would be better with a bash option, but I don't really understand how it works :) 

Thanks in advance for your help.

**Comment by YOU54F** [comment]
yes, that would be preferable. I have been working on a feature which will upload the artefacts to s3 and construct the url to retrieve them and put them in the slack message, but the artefacts could be stored anywhere.

If you have got it working you can pass in an optional flag or set an env var that is picked up, if it is set and replaces the value you refer to in `getArtefactUrl()`

**Comment by YOU54F** [comment]
Will have a look when I get some time but feel free to submit a PR if you get the chance

**Comment by kevindepoortere** [comment]
Thank you, I will have a look this weekend.

**Comment by saikatharryc** [comment]
I've been looking for this from the last couple of days. 
this is much needed, 
it will be awesome to set the `Test Report` link from the cli itself.

**Comment by marlenemaiobarroso12** [comment]
How you getArtefactUrl?
I'm using azure.... and Slack I cannot open the link correctly.....

**Comment by YOU54F** [comment]
Thanks @saikatharryc for the PR, all contributions are really appreciated! 

Will take a look now. I could do with refactoring the scripts at some point, but agree the configurabilty of the artefact url is a really good feature, as it would help those who keep their reports off their CI systems, but also open up the scope to use this on other CI systems, other than circle. I have an outstanding feature to upload reports to s3 and return the URL so it can be used in the slack message, but never finished it!

**Comment by YOU54F** [comment]
Hi @marlenemaiobarroso12 unless you are using the referenced PR, there is no current way. If you can me documentation as to how an artefact url is constructed in azure, it would be helpful in supporting. 

Any env vars that azure exposes are helpful too, especially vcs metadata. Please feel free to raise a seperate issue to support Azure 👍

**Comment by saikatharryc** [comment]
@kevindepoortere now we can set custom artifact URL, like this: `--ci-provider custom --custom-url=http://example.com`
NOTE: This will also send you videos and screenshots along in the slack message, which you might need to change location.
if you don't want those, you can set some different dirs for `--screenshots-dir` and `--videos-dir`

**Comment by saikatharryc** [comment]
@marlenemaiobarroso12 are you talking about azure pipelines?
as per I know, after building cypress, you need to host the reports (static files) in some location, it might be S3 / git pages.

then you can set the link to the HTML page of the report and also the artifacts (image and videos) can be accessible.

**Comment by kevindepoortere** [comment]
@saikatharryc Thanks a lot for your work.
I just made the upgrade and I try it right now.

**Comment by kevindepoortere** [comment]
@saikatharryc It works perfectly. Many thanks.

**Comment by kevindepoortere** [comment]
Hello @YOU54F For me it's ok, because I just need to have custom URI for reportDir (videos and screenshot links).
So it will work.

**Comment by HernanMinted** [comment]
> @kevindepoortere now we can set custom artifact URL, like this: `--ci-provider custom --custom-url=http://example.com` it's available from version `v0.7.1` NOTE: This will also send you videos and screenshots along in the slack message, which you might need to change location. if you don't want those, you can set some different dirs for `--screenshots-dir` and `--videos-dir`

So custom-url you should point to your pipeline run? didn't get quite this part, or is just to the project you have running? 🤔

**Comment by rom1gal** [comment]
Hi @YOU54F ! Any news regarding the upload to S3 ? :-)

**Comment by YOU54F** [comment]
Hey @rom1gal 

the s3 upload code is written

https://github.com/YOU54F/cypress-slack-reporter/blob/master/src/uploads3/upload.new.ts

but not currently exported at the minute, as needed wiring up for public consumption and generally the codebase wants a rewrite and I don’t really have the time.

I’ll see if I can get round to it at some point, but currently my spare OSS time is being spent learning about Rust :)
