### ISSUE TITLE
Asset URLs seem to be broken

### ISSUE THREAD

**Issue by bizmonogatari** [YOU54F/cypress-slack-reporter#551]
Hi thanks for the awesome work!

The links to assets in my slack notifications are of the form:

```
https://78-undefined-gh.circle-artifacts.com/0/cypress/videos/imageSlugGenerator/ImageSlugGenerator.tsx.mp4
```

I'm not sure why theres an undefined in there.. does anybody know?

Thanks!

**Comment by YOU54F** [comment]
please see https://github.com/YOU54F/cypress-slack-reporter/pull/446

**Comment by bizmonogatari** [comment]
Thanks for the quick response! I set the environment variable and now its purring like a kitten!
