### ISSUE TITLE
Example script link is broken in readme.md

### ISSUE THREAD

**Issue by you1anna** [YOU54F/cypress-slack-reporter#622]
Example script link gives a 404: https://github.com/YOU54F/cypress-slack-reporter/blob/master/cli/spec.ts

**Comment by YOU54F** [comment]
Thanks @you1anna - fixed now

**Comment by you1anna** [comment]
Thanks @YOU54F  I also had a couple of questions, where would be the best place to raise these?

**Comment by YOU54F** [comment]
Feel free to raise a separate issue for questions as they can be marked as such 👍
