### ISSUE TITLE
Not able to execute npx cypress-slack-reporter - `find mochareports` 

### ISSUE THREAD

**Issue by rchovatiya88** [YOU54F/cypress-slack-reporter#69]
Hi! 

 ## Thanks so much creating this plugin! 🥇 💯 👍 

 I'm having issues running the execution part `npx cypress-slack-reporter` 

`npx cypress-slack-reporter
Error: Cannot find test report @ /Users/ronakchovatiya/Documents/Work/.../mochareports`

*Specifically*
Set the following environment variables in your localhost or CI configuration. 🤔

`i've created config.env.test file  with my slack webhook`
$SLACK_WEBHOOK_URL - The full URL you created in the last step 
`where does the export go?`
$ export SLACK_WEBHOOK_URL=yourWebhookUrlHere - 

Execution
$ npx cypress-slack-reporter --help - `this works`

## Steps performed

- yarn add cypress-slack-reporter --dev
- yarn add mocha @5.4.2 (instead of the latest 6 which gave error) 
- yarn Added all of mochawesome reports (if i add the --reporter flag it works and i do get a html report) 
- Created Slack app and Webhook URL / Oauth
- added code snippets for cypress.json and reporterOpts.json
- I'm not using CIRCLE CI - need it to just run locally for now then will add gitlab later
---

Guess the main issue I'm faceing not know how to hook up the config.test.env file in my react app and error message for not finding `mochareports` i even created folder with same name in the specified place. 

*P.S* - i've tried the same steps for the example repo you've created `react-ts-testing-example`  Which has all setup - i am able to run the website locally and normal cypress test pass.. But 😓 not able to run `npx cypress-slack-reporter` 

## System Info 

MacOS
Cypress : `3.3.0`
"cypress-slack-reporter": "^0.2.6",
"mocha-multi-reporters": "^1.1.7",
"mochawesome": "^3.1.2",
"mochawesome-merge": "^1.0.7",
"mochawesome-report-generator": "^3.1.5",

--

Thanks again! 🙏

**Comment by YOU54F** [comment]
Hey buddy, thanks for using my plugin! woop woop!

Let's see what we can sort.

> `yarn add mocha @5.4.2` (instead of the latest 6 which gave error) - 

Yeah Mocha 6 errors with mocha-multi-reporters, I have fixed it in a fork, and it is available here https://www.npmjs.com/package/cypress-multi-reporters


> i've created config.env.test file with my slack webhook
$SLACK_WEBHOOK_URL - The full URL you created in the last step
where does the export go?
$ export SLACK_WEBHOOK_URL=yourWebhookUrlHere -

`config.env.test` is actually used for the projects tests, and isn't read by the npm module.

The plugin reads it with `process.env` [here](https://github.com/YOU54F/cypress-slack-reporter/blob/bdcc27c90edadec1aaf29a784c19b5c7e4e56be4/src/slack/slack-alert.ts#L23)

You need it available to the shell you are executing your program from. 

if you run the command `export SLACK_WEBHOOK_URL=https://hooks.slack.com/services/AAA/BBB/CCC` at the command line, and then run `echo $SLACK_WEBHOOK_URL` it should return your incoming webhook. However we need to look at why we can't find the report file(s).

>I'm having issues running the execution part npx cypress-slack-reporter
```
npx cypress-slack-reporter Error: Cannot find test report @ /Users/ronakchovatiya/Documents/Work/.../mochareports
```

If you run it with `npx cypress-slack-reporter --logger`, it will output the directory we are trying to read the report file from.

The report folder will need 2 things, a mochawesome html report, and a mochawesome json report. It uses the json report to ascertain the test results, and choose which message to send, and the html report is used when constructing the artefact URL's from circleci.

Let me know how it goes!

**Comment by YOU54F** [comment]
@rchovatiya88 start with passing `--logger` flag and let me know what the contents of the reportDir that the logger info provides

**Comment by YOU54F** [comment]
> P.S - i've tried the same steps for the example repo you've created react-ts-testing-example Which has all setup - i am able to run the website locally and normal cypress test pass.. But 😓 not able to run npx cypress-slack-reporter

Do you get the same error in this project about being unable to find the report, or does it complain about the webhook url not being set? If the latter then this should hopefully help!

```sh
➜  export SLACK_WEBHOOK_URL=yourWebhookUrlHere
➜  echo $SLACK_WEBHOOK_URL
yourWebhookUrlHere
```

**Comment by rchovatiya88** [comment]
Thanks for quick reply! 

so Logger  shows it should be same not why it can't find it... 
 ```» npx cypress-slack-reporter --logger  
 ciProvider:- circleci
 vcsProvider:- github
 reportDirectory:- /Users/ronakchovatiya/Documents/Work/client/mochareports
 videoDirectory:- /Users/ronakchovatiya/Documents/Work/client/cypress/videos
 screenshotDirectory:- /Users/ronakchovatiya/Documents/Work/client/cypress/screenshots

Error: Cannot find test report @ /Users/ronakchovatiya/Documents/Work/client/mochareports```

**Comment by YOU54F** [comment]
np, on the lappy doing some bits and bobs - have you got both a `.json` & `.html` file in `/Users/ronakchovatiya/Documents/Work/client/mochareports`?

**Comment by YOU54F** [comment]
Looks like the error message is coming from this function, so it can't find the html report, can you show me the output of `ls /Users/ronakchovatiya/Documents/Work/client/mochareports`

```
export function getHTMLReportFilename(reportDir: string) {
  const reportHTMLFullPath = getFiles(reportDir, ".html", []);
  if (reportHTMLFullPath.length === 0) {
    throw new Error(`Cannot find test report @ ${reportDir}`);
  } else if (reportHTMLFullPath.length >= 2) {
    throw new Error(
      "Multiple reports found, please provide only a single report"
    );
  } else {
    reportHTMLFilename = reportHTMLFullPath
      .toString()
      .split("/")
      .pop() as string;
    return reportHTMLFilename;
  }
}
```

**Comment by rchovatiya88** [comment]
ah `/mochareports` is manual folder i created, it doesn't have any files.

**Comment by YOU54F** [comment]
ahhh right, yeah that'll do it, if you run cypress, with the reporterOpts as described in the readme, you would need to do the following to generate the necessary reports

```
combine-reports:
	npx mochawesome-merge --reportDir cypress/reports/mocha > mochareports/report.json

generate-report:
	npx marge mochareports/report.json -f report -o mochareports

slack-alert:
	npx cypress-slack-reporter --logger
```

If you want to test it out, pop these two files in your mochareports folder and you should be able to send the slack message

https://github.com/YOU54F/cypress-slack-reporter/tree/master/src/slack/test/jsonTestPass

**Comment by rchovatiya88** [comment]
Superb!! it worked 👍  Thanks so much! 

**_Now on to running cypress on MsEdge on my Mac_** 🤗

>  only if someone(you!!) had written a blog post about how to do that haha 🙏 Thanks for all your contributions! i owe a cup of☕️ or 🍺 next time you're in NYC 😺

**Comment by YOU54F** [comment]
Cheers buddy! Glad it has worked for you! Good luck with Edge!

Thanks for the offer of a coffee! I've only been to America once (to NYC for a work conference) but plan on going out there with the wife soon, so you never know, might take you up on that 😆

**Comment by tusharnuk371** [comment]
can somebody let me know where we can add SLACK_WEBHOOK_URL in package.json?

**Comment by YOU54F** [comment]
> can somebody let me know where we can add SLACK_WEBHOOK_URL in package.json?

You need it as an env var in your shell, not in your package json.

**Comment by tusharnuk371** [comment]
> > can somebody let me know where we can add SLACK_WEBHOOK_URL in package.json?
> 
> You need it as an env var in your shell, not in your package json.

I am not able to pass --env SLACK_WEBHOOK_URL=yourWebhookUrlHere or export it in cypress.json. Can you please let me know how to pass it in shell?

**Comment by tusharnuk371** [comment]
Thanks for this wonderful package @YOU54F. Can we update this with following things if possible- 

1.Adding the html link as well in slack message to see mochawesome report in URL
2.Total no of tests- How many passed, how many failed , how many skipped

**Comment by YOU54F** [comment]
> > > can somebody let me know where we can add SLACK_WEBHOOK_URL in package.json?
> > 
> > 
> > You need it as an env var in your shell, not in your package json.
> 
> I am not able to pass --env SLACK_WEBHOOK_URL=yourWebhookUrlHere or export it in cypress.json. Can you please let me know how to pass it in shell?

Run export SLACK_WEBHOOK_URL=yourWebhookUrlHere in Mac or Linux

Or set SLACK_WEBHOOK_URL=yourWebhookUrlHere if running windows

Prior to running cypress-slack-reporter

**Comment by YOU54F** [comment]
> Thanks for this wonderful package @YOU54F. Can we update this with following things if possible-
> 
> 1.Adding the html link as well in slack message to see mochawesome report in URL

There is a link to the mochawesome report via a button which opens a url if using circleci

> 2.Total no of tests- How many passed, how many failed , how many skipped

There isn’t how many skipped, I can add that, but there is how many passed and failed. See the main readme for screenshots of the messages. Hope that helps

**Comment by tusharnuk371** [comment]
Thanks @YOU54F for the ideas, i created one sh script to run SLACK_WEBHOOK_URL just before cypress-slack-reporter. 

But i am not getting proper test report when i ran  this in **circleci**. I got a json page with message as artifact not found. Any suggestion on that on how to fix it?
