### ISSUE TITLE
Missing slack video links (release v1.0.0)

### ISSUE THREAD

**Issue by robipresotto** [YOU54F/cypress-slack-reporter#706]
v0.9.0
![by Robitto 2020-07-28 at 15 52 48](https://user-images.githubusercontent.com/3818948/88674930-afe27500-d0ea-11ea-8fd1-b02165cb8d14.png)

v1.0.0
![by Robitto 2020-07-28 at 15 53 02](https://user-images.githubusercontent.com/3818948/88674966-b53fbf80-d0ea-11ea-9806-142c78a00156.png)

```shell
npm install cypress --save-dev
npm install mochawesome --save-dev
npm install mochawesome-merge --save-dev
npm install mochawesome-report-generator --save-dev
npm install cypress-multi-reporters --save-dev
npm install cypress-slack-reporter --save-dev

export SLACK_WEBHOOK_URL=XXXXXXXXXXXXX

npm run cy:run --record --key pixotope-cloud

mkdir cypress/reports/mochareports/
mkdir cypress/screenshots
npx mochawesome-merge ./cypress/reports/mocha/*.json > cypress/reports/mochareports/output.json

npx marge cypress/reports/mochareports/output.json -f pixotope-cloud-report -o cypress/reports/mochareports/


npx cypress-slack-reporter \
--custom-url=${HTTP_URL} \
--report-dir=cypress/reports/mochareports \
--screenshot-dir=cypress/screenshots \
--video-dir=cypress/videos \
--ci-provider=aws \
--verbose
```

**Comment by robipresotto** [comment]
it's returning on v1.0.0

`
{"level":30,"time":1596184372472,"pid":2629,"hostname":"438750b4110b","data":{"attachments":[{"color":"#36a64f","fallback":"Report available at xxx/cypress/reports/mochareports/pixotope-cloud-report.html","text":"Total Passed:  144","actions":[{"type":"button","text":"Test Report","url":"xxx/cypress/31-07-2020-08-32AM/cypress/reports/mochareports/pixotope-cloud-report.html","style":"primary"},{"type":"button","text":"Build Logs","url":"undefined","style":"primary"}]}],"unfurl_links":false,"unfurl_media":false},"msg":"passing run"}
--
1124 | {"level":30,"time":1596184372682,"pid":2629,"hostname":"438750b4110b","result":{"text":"ok"},"testStatus":{"totalSuites":25,"totalTests":144,"totalPasses":144,"totalFailures":0,"totalDuration":257821,"reportFile":["/codebuild/output/src398575136/src/cypress/cypress/reports/mochareports/output.json"],"status":"passed"},"msg":"Slack message sent successfully"}
`

cypress.json 
`{
  "baseUrl": "https://xxxxxxxxxxx",
  "projectId": "pixotope-cloud",
  "video": true,
  "reporter": "cypress-multi-reporters",
  "reporterOptions": {
    "configFile": "reporterOpts.json"
  },
  "viewportHeight": 900,
  "viewportWidth": 1440
}`

reporterOpts.json
`{
  "reporterEnabled": "mochawesome",
  "mochawesomeReporterOptions": {
    "reportDir": "cypress/reports/mocha",
    "quiet": true,
    "overwrite": false,
    "html": false,
    "json": true
  }
}
`

any clue?

**Comment by YOU54F** [comment]
Hi @robipresotto, apologies for the late reply and thank you the report. Sorry to hear about the regression. I think this is due to using customUrl and a custom ciProvider and some changes around that logic. When I find out what the issue is, I will make sure there is a test to suite. I have a repository which is called cypress-slack-reporter-issues, if you can raise an example in a fork of that I will take a look asap One evening this week. I’ve been busy tinkering in the garage so haven’t had much coding time.

I see you are using codebuild. I’d like to support that as a Ci provider. Have you got a link to any of the env vars the build runner exposes that the ci jobs run on?

Also in your examples, where are your artefacts stored? In cypress/videos/*.mp4 against your custom url?

**Comment by robipresotto** [comment]
Hello, thanks for getting in touch :)

So the HTTP_URL is made like that:
```shell
DATE=$(date +"%d-%m-%Y-%I-%M%p")
S3_PATH=s3://xxxxxxxx/cypress/${DATE}/cypress
HTTP_URL=https://xxxxxxxxxx.s3-eu-west-1.amazonaws.com/cypress/${DATE}/
```

then we use the `S3_PATH` to push the artifacts to S3
```shell
aws s3 sync ./cypress/reports ${S3_PATH}/reports
aws s3 sync ./cypress/screenshots ${S3_PATH}/screenshots
aws s3 sync ./cypress/videos ${S3_PATH}/videos
```

then we run the slackreporter straightway
```shell
npx cypress-slack-reporter \
--custom-url=${HTTP_URL} \
--report-dir=cypress/reports/mochareports \
--screenshot-dir=cypress/screenshots \
--video-dir=cypress/videos \
--ci-provider=aws \
--verbose
```

**Comment by YOU54F** [comment]
fix inbound in v1.0.3, should be released shortly as it goes through CI. Thanks @robipresotto for the report and using the software 🚀 

https://github.com/YOU54F/cypress-slack-reporter/commit/4f61458db7e1e4f6c56d4b21fcd43e0c851bb4c3#diff-2651c65fba33da63754eba5378ff134aR128

**Comment by YOU54F** [comment]
Please re-open if an issue, thanks fella!

**Comment by robipresotto** [comment]
Thanks for looking into that,

The slack msg got the video links but the links seem to be broken. 
Are you pending the CODEBUILD_SRC_DIR env to the video URL?
It doesn't for the HTML report but it does for the videos URL.

Test report
`https://xxxxxxxxx/cypress/12-08-2020-09-06AM/cypress/reports/mochareports/pixotope-cloud-report.html`

Test videos url
`https://xxxxxxxxx/cypress/12-08-2020-09-06AM//codebuild/output/src646768641/src/cypress/cypress/videos/admin/admin-analytics.spec.js.mp4`

**Comment by YOU54F** [comment]
Are there the urls in the message link? There is a double slash that I
probably need to trim the arftefact url to not contain the absolute path
and just relative

**Comment by robipresotto** [comment]
Yep, so are you using the `CODEBUILD_SRC_DIR ` env var?

It appends it to the path of the video (codebuild/output/src646768641/src/cypress) but doesn't on the report path.
I do not use it (CODEBUILD_SRC_DIR) on my code, so guessing it's coming from your side.

**Comment by robipresotto** [comment]
But yeah, it seems like if you use only the relative path it could work 👍🏻

**Comment by robipresotto** [comment]
Are you planning to fix it soon?
