### ISSUE TITLE
Slack video link is incorrect for --custom-url

### ISSUE THREAD

**Issue by you1anna** [YOU54F/cypress-slack-reporter#979]
Hi @YOU54F, I'm also seeing this [issue](https://github.com/YOU54F/cypress-slack-reporter/issues/706#issuecomment-673336931), which doesn't seem to be resolved?  

When using

`--ci-provider custom --custom-url "${GOCDURL}" `

the resulting video artifact path in Slack is

https://xxxx/files/test_DOCKER_core_cypress_debug/7/run_all/1/run_all//var/go/rg_cypress/cypress/videos/PR/xx.spec.js.mp4

note the `//var/go/rg_cypress` is not needed, the relative path should work.

Also if `--video-dir 'rg_cypress/cypress/videos'` is added, there are no video urls output to Slack at all.

Please could this be looked into? Thanks

**Comment by YOU54F** [comment]
Hey @you1anna can you try out `1.1.0-alpha` it should hopefully help. I won't get a chance to try it out until I'm at work, but just had 10 minutes spare to have a look. Didn't realise that issue was reopened!

re: `--video-dir 'rg_cypress/cypress/videos'`, it needs to be relative to your package.json so should probably be `--video-dir 'cypress/videos'` (but actually not required)

**Comment by you1anna** [comment]
Thanks @YOU54F. In 1.1.0-alpha and the paths are improved but I'll need to test it a bit more tomorrow hopefully, will feedback asap.

Just fyi I accidentally installed 1.1.2-alpha initially and there was no post to slack.

**Comment by you1anna** [comment]
Hi @YOU54F I have managed to do some testing on 1.1.0-alpha 

Full command being run:
`yarn cy:run:${CYPRESS_SUITE} || npx cypress-slack-reporter --ci-provider custom --custom-url "${GOCDURL}/go/files/${GO_PIPELINE_NAME}/${GO_PIPELINE_COUNTER}/${GO_STAGE_NAME}/${GO_STAGE_COUNTER}/${GO_JOB_NAME}" --video-dir 'videos' --vcs-provider bitbucket --report-dir 'mochawesome-report' --verbose true`

**This is the actual link to the video artefact:**
https://gocdxxx/go/files/test_DOCKER_core_cypress_debug/12/run_all/1/run_all/videos/ecards.spec.js.mp4


Various tests on --videos-dir param:

`—video-dir  'cypress/videos'`
Video output link:
https://gocdxxx/go/files/test_DOCKER_core_cypress_debug/14/run_all/1/run_all/ecards.spec.js.mp4 
Result: missing /videos/

`—video-dir  ‘cypress’`
Video output link:
https://gocdxxx/go/files/test_DOCKER_core_cypress_debug/16/run_all/1/run_all/ecards.spec.js.mp4
Result: missing /videos/

`—video-dir  ‘videos’`
Result: No video output links 


`—video-dir  'cypress/videos/videos’`
Result: No video output links 


— no videos dir specified
No video output links

It currently does not seem possible to get the path to resolve to `/videos/ecards.spec.js.mp4`, could you suggest anything else to try? Thanks

**Comment by you1anna** [comment]
Hi @YOU54F 
Appreciate you must be busy but I wondered if you had had a chance to look at this. The artefact location is the last bit we need to get working before we can use this tool properly. 

Potentially it could work if we output artefacts to the root, but would be good not to have to modify the video location from our end if at all possible.

**Comment by YOU54F** [comment]
Hey sorry, I've been super busy of late. 

So if I understand, you are storing your video and screenshot artefacts in a subfolder of your customUrl, but that path or the artefacts, is not the location of the videos and screenshots from your test run.

so you want

- to pass a custom url which is a base path for your stored test artefacts
- to provide a custom sub path for the report/video/screenshot on the custom url
- to provide a video or screenshot directory on which to search for screenshots and videos to construct links.

I don't believe the 2nd use case is supported when the customUrl work was done, it will just default to the customUrl path.


Just fyi,  you can deploy your own version to npm to easily pull it in and test it out
- pull down this repo
- run `yarn install`
- update package.json and scope the package name to your npm account `ie @robin/cypress-slack-reporter`
- make your code changes in https://github.com/YOU54F/cypress-slack-reporter/blob/4f61458db7e1e4f6c56d4b21fcd43e0c851bb4c3/src/slack/slack-alert.ts
- run `yarn run compile` to build the source code
- you can then publish it with `npm publish --access-public` and then you can run `npx @robin/cypress-slack-reporter`

**Comment by YOU54F** [comment]
my latest source code in on my other laptop and I need to push it to remote but could you try
`npx cypress-slack-reporter@1.1.6-alpha` - I think this _may_ work but be missing a `/` on one of the joins. lmk

**Comment by you1anna** [comment]
Thanks,the cases you describe above are accurate for our setup. Will try asap this week.

I think I tried 1.1.6-alpha and it was missing a '/' but will experiment with this version as well.

Interesting, will look at publishing a scoped version as well and post any questions here, thanks.

**Comment by you1anna** [comment]
Looking at `1.1.6-alpha` the output is `run_all/1/run_allcypress/videos/PR/ecards.spec.js.mp4`
The correct relative path is  `/cypress/videos/PR/ecards.spec.js.mp4` so if the missing slash is added, it looks like it work work.

**Comment by YOU54F** [comment]
Ace, ill push a fix up after work matey thanks for your time testing

**Comment by YOU54F** [comment]
`1.1.7-alpha` just released now @you1anna

PR here https://github.com/YOU54F/cypress-slack-reporter/pull/988

**Comment by you1anna** [comment]
@YOU54F Our project is fairly large so the turnaround time with our CI is slow, sorry. I have some results:

v1.1.7-alpha
**Videos**
Actual file location:
`https://gocd.aws.net/go/files/test_DOCKER_core_cypress_debug/9/run_all/1/run_all/videos/instant-awards.spec.js.mp4`

cypress-slack-reporter link output:
`https://gocd.aws.rewardgateway.net/go/files/test_DOCKER_core_cypress_debug/9/run_all/1/run_all/cypress/videos/PR/instant-awards.spec.js.mp4 `

I think if we copy the whole file tree structure across from build output to storage location, then it should work, will change it in CI and confirm.

**Screenshots**
`https://gocd.aws.net/go/files/test_DOCKER_core_cypress_debug/9/run_all/1/run_all/cypress/screenshots/PR/nominations.spec.js/Rewards%20&%20Recognition%20--%20--%20Should%20send%20and%20approve%20a%20%20from%20Site1%20(failed).png`

Shouldn't include the filename I think `/nominations.spec.js`?

**Comment by you1anna** [comment]
The report also looks like this
`https://gocd.aws.net/go/files/test_DOCKER_core_cypress_debug/9/run_all/1/run_allmochawesome-report/mochawesome.html`

Missing `/`. If I add a `/` into the --report-dir param it fails to output any links. 

Will also try editing `slack-alert.ts` and publishing the package, just not sure how far I'll be able to get.

**Comment by you1anna** [comment]
We've managed to get videos and screenshot links working!

There are two remaining issues:

- If I add / in the end of `custom-url` then it has a double // for screenshost and videos. Do you know why this is happening?
- mochawesome-report is missing `/` between `run_all` and `mochawesome-report` directory.  Here is the command used:
npx cypress-slack-reporter --ci-provider custom --custom-url "${GOCDURL}" --report-dir mochawesome-report --verbose true --video-dir videos --screenshot-dir screenshots

**Comment by YOU54F** [comment]
I am joining the url or artefact path with the provided directory and join
it with forward slashes. I can probably trim leading and trailing slashes
and then join the paths safely. Caused me no pain of bother this globby
upgrade alongside a refactor, I should have learned my lesson and stopped
doing several things in single PR’s. ( but I probably won’t 😂)

No worries about the feedback cycle. My current client is weening off
cypress and moving to testcafe so we are still on an old version of the
slack reporter and like v3 of cypress 😂 it’s at what v7 now? It’ll be past
mocha soon.

Will probably get back on the cypress train soon, as moving clients in the
near future woop.

**Comment by you1anna** [comment]
Yes, because it seems to work for screenshots/videos, it's just the report that doesn't have the / for `--report-dir`.

I know what you mean, I have the same problem upgrading Cypress 5.7 (current in CI) to v6.7. Migration has been going on so long they have now released 7.1 😂

**Comment by samswartz13** [comment]
@YOU54F Was wondering if there was any progress made here? I am also using `--custom-url` for a project, and I believe it's this line that's causing the issue: 
https://github.com/YOU54F/cypress-slack-reporter/blob/2c622e1356b2357e3797f99923f1dae2c4e21494/src/slack/slack-alert.ts#L644

When `buildHTMLReportURL ` calls `getArtefactUrl` with a `customUrl` it doesn't add a trailing slash, which creates the incorrect URL with the missing /

**Comment by YOU54F** [comment]
sorry mate, been sidetracked with work stuff and other projects,  will try
and get on it this but will happily accept a PR. what do you reckon, we
should check if they have trailings slashes and add if not?

**Comment by samswartz13** [comment]
@YOU54F happy to put up a PR - I cloned and have the fix + some additional tests locally, but I need permission to push to the repo

**Comment by YOU54F** [comment]
Cool beans. If you fork the repo and put your changes on a branch you will
be able to create an pr again the main repo. You can always delete your
fork once the pr is complete. 🤙

**Comment by you1anna** [comment]
Hi @YOU54F and @samswartz13 
I've created/published a scoped package with the fix (I hope) to
  "name": "@you1anna/cypress-slack-reporter"

The repo is https://github.com/you1anna/cypress-slack-reporter. Not added any tests but should be able to test it this week at work if things aren't too busy 👍

**Comment by you1anna** [comment]
@YOU54F 
Testing the change I made above in CI, the test report link now works 👍 but the artefact paths are now broken again :(

actual location
https://gocd.net/go/files/test_DOCKER_core_cypress_scheduled_recognition/10/run_all/1/run_all/videos/4-scheduled-recognition.spec.js.mp4

reporter output location
https://gocd.net/go/files/test_DOCKER_core_cypress_scheduled_recognition/10/run_all/1/run_all/var/go/rg_cypress/videos/4-scheduled-recognition.spec.js.mp4

the `/var/go/rg_cypress/` is not needed, think it's using the path from the root.

**Comment by you1anna** [comment]
Thanks both, on `1.1.9-alpha` we are not seeing the `/mochawesome-report` dir being created in CI, although it works locally for some reason. Guessing this could be related to the failures above?

@YOU54F I think I used master, apologies.

**Comment by you1anna** [comment]
@YOU54F we had some permission issues that were preventing the `/mochawesome-report` being created in CI following an upgrade. So `1.1.9-alpha` seems to work for report **and** artefacts. Sorry for any confusion, glad it's working.

**Comment by YOU54F** [comment]
Excellent news matey, no worries, just glad its all working now. Will get the PR merged, and released as 1.2.0 👍🏾
