### ISSUE TITLE
Confusing "Multiple html reports found" Error message

### ISSUE THREAD

**Issue by Gentoli** [YOU54F/cypress-slack-reporter#984]
https://github.com/YOU54F/cypress-slack-reporter/blob/6738b44448cb3ce3479da6729f8e28bde0b37ce2/src/slack/slack-alert.ts#L472

This message shows when there is no html file.

**Comment by YOU54F** [comment]
Good shout! I'll update that now, as I am making a couple of changes

**Comment by YOU54F** [comment]
updated fix in `1.1.8-alpha` thanks for the issue @Gentoli
